import type { Metadata } from "next";
import {ClerkProvider} from '@clerk/nextjs'
import { Nunito } from "next/font/google";
import "./globals.css";

const geistnunito = Nunito({  subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body className={geistnunito.className}>
        <ClerkProvider>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
